import Attribute from "./attribute";
import ClassName from "./className";
import Combinator from "./combinator";
import Comment from "./comment";
import Id from "./id";
import Nesting from "./nesting";
import Pseudo from "./pseudo";
import Root from "./root";
import Selector from "./selector";
import Str from "./string";
import Tag from "./tag";
import Universal from "./universal";

export const attribute = /* @__PURE__ */ (opts) => new Attribute(opts);
export const className = /* @__PURE__ */ (opts) => new ClassName(opts);
export const combinator = /* @__PURE__ */ (opts) => new Combinator(opts);
export const comment = /* @__PURE__ */ (opts) => new Comment(opts);
export const id = /* @__PURE__ */ (opts) => new Id(opts);
export const nesting = /* @__PURE__ */ (opts) => new Nesting(opts);
export const pseudo = /* @__PURE__ */ (opts) => new Pseudo(opts);
export const root = /* @__PURE__ */ (opts) => new Root(opts);
export const selector = /* @__PURE__ */ (opts) => new Selector(opts);
export const string = /* @__PURE__ */ (opts) => new Str(opts);
export const tag = /* @__PURE__ */ (opts) => new Tag(opts);
export const universal = /* @__PURE__ */ (opts) => new Universal(opts);
